name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  CARGO_TERM_COLOR: always

jobs:
  build_linux:
    name: Build Binary for Linux
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release --target x86_64-unknown-linux-gnu
      - run: mkdir release
      - run: mv target/x86_64-unknown-linux-gnu/release/image-hidden-message .
      - run: tar -czvf image-hidden-message.tar.gz image-hidden-message
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "image-hidden-message.tar.gz"
          allowUpdate: true
